/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Settings
 */
export interface Settings {
    /**
     * Whether to use MinerU
     * @type {boolean}
     * @memberof Settings
     */
    'use_mineru'?: boolean;
    /**
     * API token for MinerU
     * @type {string}
     * @memberof Settings
     */
    'mineru_api_token'?: string;
    /**
     * Whether to use DocRay
     * @type {boolean}
     * @memberof Settings
     */
    'use_doc_ray'?: boolean;
    /**
     * Whether to use MarkItDown
     * @type {boolean}
     * @memberof Settings
     */
    'use_markitdown'?: boolean;
    /**
     * PaddleOCR service URL
     * @type {string}
     * @memberof Settings
     */
    'paddleocr_host'?: string;
    /**
     * Whisper service URL
     * @type {string}
     * @memberof Settings
     */
    'whisper_host'?: string;
    /**
     * Chunk size for document parsing
     * @type {number}
     * @memberof Settings
     */
    'chunk_size'?: number;
    /**
     * Chunk overlap size for document parsing
     * @type {number}
     * @memberof Settings
     */
    'chunk_overlap_size'?: number;
    /**
     * Token size for graph chunking
     * @type {number}
     * @memberof Settings
     */
    'kg_chunk_token_size'?: number;
    /**
     * Token overlap size for graph chunking
     * @type {number}
     * @memberof Settings
     */
    'kg_chunk_overlap_token_size'?: number;
    /**
     * Max gleaning rounds for entity extraction
     * @type {number}
     * @memberof Settings
     */
    'kg_entity_extract_max_gleaning'?: number;
    /**
     * Max concurrent LLM calls for graph processing
     * @type {number}
     * @memberof Settings
     */
    'kg_llm_model_max_async'?: number;
    /**
     * Cosine similarity threshold for vector matching
     * @type {number}
     * @memberof Settings
     */
    'kg_cosine_threshold'?: number;
    /**
     * Max batch size for graph processing
     * @type {number}
     * @memberof Settings
     */
    'kg_max_batch_size'?: number;
    /**
     * Max tokens for entity/relation summaries
     * @type {number}
     * @memberof Settings
     */
    'kg_summary_max_tokens'?: number;
    /**
     * Threshold to force LLM summary when merging entities
     * @type {number}
     * @memberof Settings
     */
    'kg_force_llm_summary_on_merge'?: number;
    /**
     * Custom entity types for knowledge graph extraction
     * @type {Array<string>}
     * @memberof Settings
     */
    'kg_entity_types'?: Array<string>;
    /**
     * Maximum number of graph nodes to display (1-10000)
     * @type {number}
     * @memberof Settings
     */
    'max_graph_nodes'?: number;
    /**
     * Whether LLM cache is enabled
     * @type {boolean}
     * @memberof Settings
     */
    'cache_enabled'?: boolean;
    /**
     * Cache TTL in seconds
     * @type {number}
     * @memberof Settings
     */
    'cache_ttl'?: number;
    /**
     * Enable parent-child chunking for richer retrieval context
     * @type {boolean}
     * @memberof Settings
     */
    'parent_child_enabled'?: boolean;
    /**
     * Parent chunk size in tokens
     * @type {number}
     * @memberof Settings
     */
    'parent_chunk_size'?: number;
    /**
     * Child chunk size in tokens
     * @type {number}
     * @memberof Settings
     */
    'child_chunk_size'?: number;
    /**
     * Overlap size between child chunks in tokens
     * @type {number}
     * @memberof Settings
     */
    'child_chunk_overlap'?: number;
    /**
     * Separator for parent chunks e.g. "##". Empty = hierarchy-based
     * @type {string}
     * @memberof Settings
     */
    'parent_chunk_separator'?: string;
    /**
     * Separator for child chunks e.g. "\n\n". Empty = semantic splitting
     * @type {string}
     * @memberof Settings
     */
    'child_chunk_separator'?: string;
    /**
     * Collapse consecutive spaces, newlines and tabs
     * @type {boolean}
     * @memberof Settings
     */
    'preprocess_collapse_whitespace'?: boolean;
    /**
     * Remove all URLs and email addresses before chunking
     * @type {boolean}
     * @memberof Settings
     */
    'preprocess_remove_urls_emails'?: boolean;
}

